app-id: com.naps2.Naps2
runtime: org.freedesktop.Platform
runtime-version: '26.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.dotnet10
command: naps2
copy-icon: true
finish-args:
  # GUI
  - --socket=wayland
  - --socket=fallback-x11
  - --share=ipc
  # USB scanning
  - --device=all
  # Network scanning
  - --share=network
  # We need /usr access to read host-installed SANE backends
  # CLI/batch scanning might also need read/write access to arbitrary folders without being able to use a portal
  - --filesystem=host
  # App data
  - --filesystem=xdg-config/naps2
  # GVfs
  - --filesystem=xdg-run/gvfsd
  - --talk-name=org.gtk.vfs.*
  # mDNS discovery for ESCL scanners
  - --system-talk-name=org.freedesktop.Avahi

cleanup:
  - /include
  - /lib/*.a
  - /lib64/*.a
  - /lib/*.la
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /share/doc
  - /share/man
modules:
  - name: leptonica
    buildsystem: cmake-ninja
    builddir: true
    sources:
      - type: git
        url: https://github.com/DanBloomberg/leptonica
        tag: 1.74.4
        commit: f3d7ee868b4864cdca7ea57349d49f3d2b4a63ec
        x-checker-data:
          type: git
          tag-pattern: ^\d+(\.\d+)*$

  - name: tesseract
    buildsystem: cmake-ninja
    builddir: true
    cleanup:
      - /app/share/tessdata
    config-opts:
      - -DDISABLED_LEGACY_ENGINE=ON
      - -DBUILD_TRAINING_TOOLS=OFF
      - -DENABLE_LTO=ON
    sources:
      - type: git
        url: https://github.com/tesseract-ocr/tesseract
        tag: 5.3.4
        commit: 8ee020e14cf5be4e3f0e9beb09b6b050a1871854
        x-checker-data:
          type: git
          tag-pattern: ^\d+(\.\d+)*$

  - name: avahi
    buildsystem: autotools
    config-opts:
      - --with-distro=debian
      - --disable-libevent
      - --disable-qt4
      - --disable-qt5
      - --disable-libdaemon
      - --disable-python
      - --disable-mono
      - --disable-manpages
    sources:
      - type: git
        url: https://github.com/lathiat/avahi
        tag: v0.8
        commit: f060abee2807c943821d88839c013ce15db17b58
        x-checker-data:
          type: git
          tag-pattern: ^v([\\d.]+)$

  - name: sane
    buildsystem: autotools
    sources:
      - type: git
        url: https://gitlab.com/sane-project/backends
        tag: 1.0.32
        commit: c1c567c49b3bc9d86a5796b7fd9b17816700f75c
        x-checker-data:
          type: git
          tag-pattern: ^\d+(\.\d+)*$
      - type: patch
        path: sane-streamdevices.patch

  - name: sane-airscan
    buildsystem: meson
    sources:
      - type: git
        url: https://github.com/alexpevzner/sane-airscan
        tag: 0.99.38
        commit: 9da18d88c88f542671b24fc0433dd7d69dcb0132
        x-checker-data:
          type: git
          tag-pattern: ^\d+(\.\d+)*$

  - name: main
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/dotnet10/bin
      append-ld-library-path: /usr/lib/sdk/dotnet10/lib
      env:
        PKG_CONFIG_PATH: /app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/dotnet10/lib/pkgconfig
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      arch:
        aarch64:
          env:
            RUNTIME: linux-arm64
        x86_64:
          env:
            RUNTIME: linux-x64
    build-commands:
      - mkdir -p /app/bin
      - dotnet publish NAPS2.App.Gtk -c Release -r $RUNTIME --self-contained /p:DebugType=None
        /p:DebugSymbols=false --source ./nuget-sources
      - cp -r --remove-destination /run/build/main/NAPS2.App.Gtk/bin/Release/net10.0/$RUNTIME/publish/.
        /app/bin/
      - install -Dm644 com.naps2.Naps2.png /app/share/icons/hicolor/128x128/apps/com.naps2.Naps2.png
      - install -Dm644 com.naps2.Naps2.metainfo.xml /app/share/metainfo/com.naps2.Naps2.metainfo.xml
      - install -Dm644 com.naps2.Naps2.desktop /app/share/applications/com.naps2.Naps2.desktop
    cleanup:
      - /bin/_linuxarm/tesseract
      - /bin/_linux/tesseract
    sources:
      - type: git
        path: ../../../../../..
      - type: file
        path: com.naps2.Naps2.png
      - type: file
        path: com.naps2.Naps2.metainfo.xml
      - type: file
        path: com.naps2.Naps2.desktop
